<template>
  <div class="flex min-h-[calc(100vh-150px)] flex-col justify-center">
    <div class="space-y-5 font-bold lg:w-3/4 lg:space-y-8 2xl:space-y-12">
      
      <p class="text-primary lg:text-[1.4vw]">{{ $t('hello') }}</p>

      <h1 id="name" class="text-4xl font-bold lg:text-[4vw]">
        Pierrick TAÏLY
      </h1>

      <p class="text-lg font-semibold leading-10 lg:w-3/4 lg:text-[1.3vw]">
        {{ $t('description') }}
      </p>

      <div class="flex gap-5 font-semibold lg:text-[1vw]">
        <button class="bg-primary px-5 py-2 text-secondary hover:bg-primary/90">
          <p>{{ $t('contact') }}</p>
        </button>
        <button
          class="border border-primary px-5 py-2 text-primary hover:bg-primary hover:text-secondary"
        >
          <p>{{ $t('downloadCV') }}</p>
        </button>
      </div>

      <div class="flex gap-5">
        <NuxtLink
          to="/"
          class="transition-all duration-300 ease-in-out hover:text-primary"
        >
          <IconGithub class="h-6 w-6" />
        </NuxtLink>
        <NuxtLink
          to="/"
          class="transition-all duration-300 ease-in-out hover:text-primary"
        >
          <IconLinkedin class="h-6 w-6" />
        </NuxtLink>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import gsap from 'gsap'
import { TextPlugin } from 'gsap/TextPlugin'
gsap.registerPlugin(TextPlugin)

gsap.to('.name', {
  text: 'Pierrick TAÏLY',
  duration: 1,
  ease: 'none',
  delay: 1,
})
</script>

<style scoped>
.slide-in-bottom {
  -webkit-animation: slide-in-bottom 0.8s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
  animation: slide-in-bottom 0.8s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
}

/* ----------------------------------------------
 * Generated by Animista on 2023-11-3 14:8:57
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-in-bottom
 * ----------------------------------------
 */
@-webkit-keyframes slide-in-bottom {
  0% {
    -webkit-transform: translateY(1000px);
    transform: translateY(1000px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
    opacity: 1;
  }
}
@keyframes slide-in-bottom {
  0% {
    -webkit-transform: translateY(1000px);
    transform: translateY(1000px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
    opacity: 1;
  }
}
</style>
